mysite/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'common'

urlpatterns=[

  path('', auth_views.LoginView.as_view(template_name='search/secondmain.html'), name='login'),
  path('logout/', auth_views.LogoutView.as_view(template_name='search/firstmain.html'), name='logout'),
  path('new_account/', views.register, name='register'),
  path('forgot_id/', views.ForgotIDview, name='ForgotIDview'),
  path('login/forgot_pw/', views.ForgotPWview, name='ForgotPWview'),




]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('search.urls')),
    path('common/', include('common.urls')),
    path('', views.next_stock_search, name='next_stock_search'),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/search/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'search'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_page, name='login_page'),
    path('data_search/', views.data_search, name='data_search'),
    path('change_pw/', views.change_pw, name='change_pw'),
    path('data_search/', views.again_search_stock, name='again_search_stock'),
    path('appear_graph/', views.stock_data_graph, name='stock_data_graph'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

mysite/search/models.py
from django.db import models

# Create your models here.


class Stockname_stocks(models.Model):
    stockname = models.CharField(max_length=50)
    stockcode = models.CharField(max_length=50)
    objects = models.Manager()



class Document(models.Model):
    title = models.CharField(max_length=200)
    uploadedFile = models.FileField(upload_to="")
    dateTimeOfUpload = models.DateTimeField(auto_now=True)
    objects = models.Manager()

mysite/search/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



mysite/search/views.py

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import FinanceDataReader as fdr
from .models import Stockname_stocks
from django.contrib.auth.hashers import check_password
from django.contrib import messages, auth
from . import models
import os
from django.http import FileResponse
from django.core.files.storage import FileSystemStorage
import matplotlib.pyplot as plt
import matplotlib
import platform
# Create your views here.

def index(request):
    return render(request, 'search/firstmain.html')


def login_page(request):
    return render(request, 'search/login.html')


@login_required(login_url='common:login')
def again_search_stock(request):
    return render(request, 'search/stock_search.html')


@login_required(login_url='common:login')
def data_search(request):
        global stock_data
        global stock_name
        global stock_code
        stock_name = request.POST.get('stock_name')
        start_date = request.POST.get('startdate')
        finish_date = request.POST.get('finishdate')
        if request.method == 'POST':
            if (stock_name == "" and start_date == "" and finish_date == ""):
                messages.info(request, "주식 이름, 날짜를 설정해주세요.")
            elif (stock_name == "" and start_date == ""):
                messages.info(request, "주식 이름, 시작 날짜를 설정해주세요.")
            elif (stock_name == "" and finish_date == ""):
                messages.info(request, "주식 이름, 종료 날짜를 설정해주세요.")
            elif (start_date == "" and finish_date == ""):
                messages.info(request, "시작 날짜, 종료 날짜를 설정해주세요..")
            elif (stock_name == ""):
                messages.info(request, "주식 이름을 입력해주세요. ")
            elif (start_date == ""):
                messages.info(request, "시작 날짜를 설정해주세요.")
            elif (finish_date == ""):
                messages.info(request, "종료 날짜를 설정해주세요.")
            else:
             try:
                    if platform.system() == 'Windows':    #그래프 한글 설정
                        matplotlib.rc('font', family='Malgun Gothic')
                    elif platform.system() == 'Darwin': # Mac
                         matplotlib.rc('font', family='AppleGothic')
                    else: #linux
                         matplotlib.rc('font', family='NanumGothic')
                    stock_code = Stockname_stocks.objects.get(stockname=stock_name)
                    stock_data = fdr.DataReader(stock_code.stockcode, start_date, finish_date)
                    stock_data = stock_data.drop(['Change'], axis=1)
                    stock_data.columns = ['시가', '최고가', '최저가', '종가', '거래량']
                    stock_data.to_excel('media/{}.xlsx'.format(stock_code.stockcode))
                    fig = plt.figure()
                    mk2 = fig.add_subplot(1, 1, 1)
                    plt.plot(stock_data['종가'])
                    mk2.set_title('{}'.format(stock_name))
                    mk2.set_xlabel('Date')
                    mk2.set_ylabel('종가')
                    plt.xticks(rotation=20)
                    fig.savefig('./static/graph.png')
                    document = models.Document(
                        title=stock_name,
                        uploadedFile='media/{}.xlsx'.format(stock_code.stockcode))
                    document.save()
                    file_path = os.path.abspath("media/")
                    file_name = os.path.basename("media/{}.xlsx".format(stock_code.stockcode))
                    fs = FileSystemStorage(file_path)
                    response = FileResponse(fs.open(file_name, 'rb'), content_type='application/vnd.ms-excel')
                    response['Content-Disposition'] = 'attachment; filename=' + "{}.xlsx".format(stock_code.stockcode)
                    return response
             except:
                    messages.info(request, "검색정보가 일치하지 않습니다.")

             context = {}
             return render(request, 'search/stock_search.html', context)

        else:
            return render(request, 'search/stock_search.html')


@login_required(login_url='common:login')
def stock_data_graph(request):
    file_path = "./static/graph.png"
    if os.path.exists(file_path):
      # os.remove(file_path)
       return render(request, 'search/graph.html')
    else:
       messages.info(request, "그래프 정보가 존재하지 않습니다.")
       return render(request, 'search/stock_search.html')


@login_required(login_url='common:login')
def change_pw(request):
    user = request.user
    oringin_pw = request.POST.get('currentPassword')
    new_pw = request.POST.get('new_password12')
    confirm_pw = request.POST.get('new_password22')
    if request.method == 'POST':
                if (oringin_pw == "" and new_pw == "" and confirm_pw == ""):
                    messages.info(request, "기존 비밀번호, 새 비밀번호을 입력해주세요.")
                elif (oringin_pw == "" and new_pw == ""):
                    messages.info(request, "기존 비밀번호, 새 비밀번호를 입력해주세요.")
                elif (oringin_pw == "" and confirm_pw == ""):
                    messages.info(request, "기존 비밀번호, 새 비밀번호 확인을 입력해주세요.")
                elif (new_pw == "" and confirm_pw == ""):
                    messages.info(request, "새 비밀번호, 새 비밀번호 확인을 입력해주세요.")
                elif (oringin_pw == ""):
                    messages.info(request, "기존 비밀번호를 입력해주세요. ")
                elif (new_pw == ""):
                    messages.info(request, "새 비밀번호를 입력해주세요.")
                elif (confirm_pw == ""):
                    messages.info(request, "새 비밀번호 확인을 입력해주세요.")
                else:
                    if check_password(oringin_pw, user.password):
                            if new_pw == confirm_pw:
                                user.set_password(new_pw)
                                user.save()
                                auth.login(request, user)
                                return render(request, 'search/stock_search.html')
                            else:
                                messages.info(request, '비밀번호가 다릅니다')
                    else:
                        messages.error(request, '기존 비밀번호가 옳바르지 않습니다.')
                        return render(request, 'search/password_reset_confirm.html')
                    return render(request, 'search/password_reset_confirm.html')
    context = {}
    return render(request, 'search/password_reset_confirm.html', context)

mysite/templates/search/appear_graph.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if data %}
<img src="data:image/png;base64,{{data|safe}}">
{% endif %}
</body>
</html>

mysite/templates/search/forgot_id.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Westagram</title>
    <link rel=stylesheet href="style/login.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
</head>
<body>
    <main>
        <div class="logo">주식 존망</div>
        <form method="post">
            {% csrf_token %}
            < 아이디 찾기>
          {% for message in messages %}
            <p class="message">{{ message }}</p>
          {% endfor %}
        <article>
            <div class="login_id">
                <input type="text" placeholder="이름" class="idValue" name="first_name">
            </div>
            <div class="login_password">
                <input type="email" placeholder="이메일" class="passwordValue" name="email">
            </div>

            <div>
               <button class="login_btn" type="submit" name="email_submit">아이디 찾기</button>
            </div>

            <div class="links">
                <a href="{% url 'common:ForgotPWview'  %}">비밀번호 찾기</a> | <a href="{% url 'common:login' %}">로그인</a> | <a href="{% url 'common:register' %}">회원가입</a>

            </div>


</article>
        </form>
    </main>
    <script src='./js/login.js'></script>
</body>
</html>
<style>
    * {
    margin: 0;
    box-sizing: border-box;

}

a {
    text-decoration: none;
    color: white;
}

main {
    height: 800px;
    width: 450px;
    padding: 50px 0;
    border: #EFEFEF solid 2px;
    margin: 100px auto;
    text-align: center;
    display: flex;
    flex-direction: column;
}

.logo {
    margin-bottom: 50px;
    font-size: 50px;
    font-family: 'Lobster', cursive;
}

input {
    height: 45px;
    width: 300px;
    margin-bottom: 10px;
    background-color:#FAFAFA;
    border: #EFEFEF 1px solid;
    border-radius: 6px;
    padding-left: 10px;
}

input:focus {
    outline: none;
}

.login_btn {
    width: 300px;
    height: 35px;
    border-radius: 6px;
    border: white;
    margin-bottom: 100px;
    background-color: #C4E1FB;
    color: white;
    font-size: 17px;
}

.login_btn:hover {
    cursor: pointer;
}

footer {
    color: #345E87;
}
.noneunderline {
    text-decoration:none;
}
.haveAccount {
    background-color: #fcfcfc;
    margin-top: 10px;
    padding: 15px;
    border: 1px solid #dfdfdf;
    border-radius: 3px;
}

.haveAccount p {
    font-size: 14px;
    font-weight: 300;
    color: #333333;
}

.haveAccount p a{
    font-weight: 600;
    color: #248ae3;
}
.box {
  height: 50px;
}
.links{
        text-align: center;
        margin-bottom: 10px;
    }
    a{
       color: blue; text-decoration: none;
    }
    .text2{
       color : blue;
    }
.message{
 font-weight: bolder;
}
    </style>

mysite/templates/search/graph.html
<!DOCTYPE html><html>
<head>
     <style>
            img { display:block; margin:auto;}
        </style>

</head>
<body>

<img src="/static/graph.png" >

</body>
</html>

mysite/templates/search/login.html

<!DOCTYPE html><html>
<head>

</head>
<body>
<div class="v21_50">
<div><a href="{% url 'search:index' %}" ><button class="v21_54">Main</button></a></div>


<form method="post" class="" action="{% url 'common:login' %}">
      {% csrf_token %}
    {% include "form_errors.html" %}



    <div class="name"></div>
    <div class="v50_46">
        <label class="v21_52" for='username'>ID</label>
         <input class="v21_55" type="text" name="username" id='username'
                        value="{{ form.username.value|default_if_none:'' }}" >

    </div>
    <div class="v50_47">
    <label class="v21_53" for="password">Password</label>
         <input class="v21_56"
                 value="{{ form.password.value|default_if_none:'' }}" id="password"type="password" name="password" >
    </div>
    <a class="v21_57" href="{% url 'common:ForgotIDview'  %}">아이디 찾기</a>
    <a class="v21_58" href="{% url 'common:ForgotPWview'  %}">비밀번호 찾기</a>
    <div class="v50_48">
        <div class="v21_59">

    </div>
        <button type="submit"  class="v21_60"  >로그인 하기</button>

    </div>


</form>
</div>
</body>
</html> <br/><br/>
<style>* {
  box-sizing: border-box;
}
body {
  font-size: 14px;
}
.v21_50 {
  width: 771px;
  height: 668px;
  background: rgba(255,255,255,1);
  opacity: 1;
  position: relative;
  top: 0px;
  left: 0px;
  overflow: hidden;
}
.name {
  color: #fff;
}
.v21_54 {
  width: 80px;
  color: rgba(0,0,0,1);
  position: absolute;
  top: 27px;
  left: 25px;
  font-family: Inter;
  font-weight: Regular;
  font-size: 20px;
  opacity: 1;
  text-align: left;
}
.v50_46 {
  width: 592px;
  height: 49px;
  background: url("../images/v50_46.png");
  background-repeat: no-repeat;
  background-position: center center;
  background-size: cover;
  opacity: 1;
  position: absolute;
  top: 223px;
  left: 105px;
  overflow: hidden;
}
.v21_52 {
  width: 115px;
  color: rgba(0,0,0,1);
  position: relative;
  top: 0px;
  left: 0px;
  font-family: Inter;
  font-weight: Regular;
  font-size: 20px;
  opacity: 1;
  text-align: left;
}
.v21_55 {
  width: 592px;
  height: 21px;
  background: rgba(217,217,217,1);
  opacity: 1;
  position: absolute;
  top: 28px;
  left: 0px;
  overflow: hidden;
}
.v50_47 {
  width: 592px;
  height: 50px;
  background: url("../images/v50_47.png");
  background-repeat: no-repeat;
  background-position: center center;
  background-size: cover;
  opacity: 1;
  position: absolute;
  top: 280px;
  left: 104px;
  overflow: hidden;
}
.v21_53 {
  width: 131px;
  color: rgba(0,0,0,1);
  position: absolute;
  top: 0px;
  left: 1px;
  font-family: Inter;
  font-weight: Regular;
  font-size: 20px;
  opacity: 1;
  text-align: left;
}
.v21_56 {
  width: 592px;
  height: 21px;
  background: rgba(217,217,217,1);
  opacity: 1;
  position: absolute;
  top: 29px;
  left: 0px;
  overflow: hidden;
}
.v21_57 {
  width: 139px;
  color: rgba(0,0,0,1);
  position: absolute;
  top: 408px;
  left: 229px;
  font-family: Inter;
  font-weight: Regular;
  font-size: 13px;
  opacity: 1;
  text-align: center;
}
.v21_58 {
  width: 145px;
  color: rgba(0,0,0,1);
  position: absolute;
  top: 408px;
  left: 400px;
  font-family: Inter;
  font-weight: Regular;
  font-size: 13px;
  opacity: 1;
  text-align: center;
}
.v50_48 {
  width: 233px;
  height: 37px;
  background: url("../images/v50_48.png");
  background-repeat: no-repeat;
  background-position: center center;
  background-size: cover;
  opacity: 1;
  position: absolute;
  top: 352px;
  left: 274px;
  overflow: hidden;
}
.v21_59 {
  width: 233px;
  height: 37px;
  background: rgba(0,0,0,1);
  opacity: 1;
  position: relative;
  top: 0px;
  left: 0px;
  border-top-left-radius: 7px;
  border-top-right-radius: 7px;
  border-bottom-left-radius: 7px;
  border-bottom-right-radius: 7px;
  overflow: hidden;
}
.v21_60 {
  width: 211px;
  color: rgba(255,255,255,1);
  position: absolute;
  top: 6px;
  left: 14px;
  font-family: Inter;
  font-weight: Regular;
  font-size: 20px;
  opacity: 1;
  text-align: center;
}
</style>

mysite/templates/search/password_reset.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Westagram</title>
    <link rel=stylesheet href="style/login.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
</head>
<body>
    <main>
        <div class="logo">주식 존망</div>
        <form method="post" class="post-form" action="">
            {% csrf_token %}
            < 비밀번호 찾기>
            {% for message in messages %}
                     <p class="message">{{ message }}</p>
            {% endfor %}

        <article>
            <div class="login_id_1">
                <input type="text" placeholder="아이디" class="idValue"  name="username">
            </div>

            <div class="login_password">
                <input type="email" placeholder="이메일" class="passwordValue" name="email">
            </div>
            <div>
               <button class="login_btn" type="submit">이메일보내기</button>
            </div>
            <div class="links">
                <a href="{% url 'common:ForgotIDview'  %}">아이디 찾기</a> | <a href="{% url 'common:login' %}">로그인</a> | <a href="{% url 'common:register' %}">회원가입</a>

            </div>





        </article>
        </form>
    </main>
    <script src='./js/login.js'></script>
</body>
</html>
<style>
    * {
    margin: 0;
    box-sizing: border-box;

}

a {
    text-decoration: none;
    color: white;
}

main {
    height: 800px;
    width: 450px;
    padding: 50px 0;
    border: #EFEFEF solid 2px;
    margin: 100px auto;
    text-align: center;
    display: flex;
    flex-direction: column;
}

.logo {
    margin-bottom: 50px;
    font-size: 50px;
    font-family: 'Lobster', cursive;
}

input {
    height: 45px;
    width: 300px;
    margin-bottom: 10px;
    background-color:#FAFAFA;
    border: #EFEFEF 1px solid;
    border-radius: 6px;
    padding-left: 10px;
}

input:focus {
    outline: none;
}

.login_btn {
    width: 300px;
    height: 35px;
    border-radius: 6px;
    border: white;
    margin-bottom: 100px;
    background-color: #C4E1FB;
    color: white;
    font-size: 17px;
}

.login_btn:hover {
    cursor: pointer;
}

footer {
    color: #345E87;
}
.noneunderline {
    text-decoration:none;
}
.haveAccount {
    background-color: #fcfcfc;
    margin-top: 10px;
    padding: 15px;
    border: 1px solid #dfdfdf;
    border-radius: 3px;
}

.haveAccount p {
    font-size: 14px;
    font-weight: 300;
    color: #333333;
}

.haveAccount p a{
    font-weight: 600;
    color: #248ae3;
}
.box {
  height: 50px;
}
.links{
        text-align: center;
        margin-bottom: 10px;
    }
    a{
       color: blue; text-decoration: none;
    }
    .text2{
       color : blue;
    }
.message{
 font-weight: bolder;
}
    </style>

mysite/templates/search/password_reset_confirm.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Westagram</title>
    <link rel=stylesheet href="style/login.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
</head>
<body>
    <main>
        <div class="logo">주식 존망</div>
        <form method="post" action="{% url 'search:change_pw' %}">
        {% csrf_token %}
         < 비밀번호 변경>
        {% for message in messages %}
           <p class="message">{{ message }}</p>
        {% endfor %}
        <article>
            <div class="login_password">
                <input type="password" placeholder="기존 비밀번호" class="passwordValue"  name="currentPassword">
            </div>
            <div class="login_id_1">
                <input type="password" placeholder="새로운 비밀번호" class="idValue" name="new_password12" >
            </div>
            <div class="login_id">
                <input type="password" placeholder="새로운 비밀번호 확인" class="idValue" name="new_password22">
            </div>
            <div>
                <button class="login_btn" type="submit">변경하기</button>
            </div>
            <div class="links">
                <a href="{% url 'search:again_search_stock'  %}">뒤로가기</a>
            </div>
</article>
</form>

    </main>
    <script src='./js/login.js'></script>
</body>
</html>
<style>
    * {
    margin: 0;
    box-sizing: border-box;

}

a {
    text-decoration: none;
    color: white;
}

main {
    height: 800px;
    width: 450px;
    padding: 50px 0;
    border: #EFEFEF solid 2px;
    margin: 100px auto;
    text-align: center;
    display: flex;
    flex-direction: column;
}

.logo {
    margin-bottom: 50px;
    font-size: 50px;
    font-family: 'Lobster', cursive;
}

input {
    height: 45px;
    width: 300px;
    margin-bottom: 10px;
    background-color:#FAFAFA;
    border: #EFEFEF 1px solid;
    border-radius: 6px;
    padding-left: 10px;
}

input:focus {
    outline: none;
}

.login_btn {
    width: 300px;
    height: 35px;
    border-radius: 6px;
    border: white;
    margin-bottom: 100px;
    background-color: #C4E1FB;
    color: white;
    font-size: 17px;
}

.login_btn:hover {
    cursor: pointer;
}

footer {
    color: #345E87;
}
.noneunderline {
    text-decoration:none;
}
.haveAccount {
    background-color: #fcfcfc;
    margin-top: 10px;
    padding: 15px;
    border: 1px solid #dfdfdf;
    border-radius: 3px;
}

.haveAccount p {
    font-size: 14px;
    font-weight: 300;
    color: #333333;
}

.haveAccount p a{
    font-weight: 600;
    color: #248ae3;
}
.box {
  height: 50px;
}
.links{
        text-align: center;
        margin-bottom: 10px;
    }
    a{
       color: blue; text-decoration: none;
    }
    .text2{
       color : blue;
    }
.message{
 font-weight: bolder;
}
    </style>



mysite/templates/search/password_reset_done.html
<div class="container my-3">
    <h4 class="border-bottom pb-2 my-3">이메일 전송 완료</h4>

    <a href="{% url 'login' %}" class="btn btn-primary">처음으로</a>
</div>

mysite/templates/search/secondmain.html

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Westagram</title>
    <link rel=stylesheet href="style/login.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
</head>
<body>

    <main>
        <form method="post" class="" action="{% url 'common:login' %}">
      {% csrf_token %}

        <div class="logo">주식 존망</div>
        <article>
            <div class="login_id">
                <input type="text" placeholder=" 사용자 계정" class="idValue"
                 name="username" value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="login_password">
                <input type="password" placeholder="비밀번호" class="passwordValue"
                 value="{{ form.password.value|default_if_none:'' }}"   name="password" >
            </div>
            <div>
                <button class="login_btn"  type="submit">로그인</button>
                 {% include "form_errors.html" %}
            </div>

            <div class="box">
            <div class="horizonAndOrWrap">
                <hr class="leftHr">
                <div class="or">또는</div>
                <hr class="rightHr">
            </div>
            <div class="noneunderline"></div>
            </div>
        </article>
        <a href="{% url 'common:ForgotIDview'  %}"><footer>
            아이디를 잊으셨나요?
            </footer></a>
        <a  href="{% url 'common:ForgotPWview'  %}"><footer>
            비밀번호를 잊으셨나요?
        </footer></a>
     </div>


        <div class="haveAccount">
            <p>계정이 없으신가요?
              <a href="{% url 'common:register' %}" class="noneunderline">가입하기</a>
            </p>
        </div>
            </form>
    </main>


</body>
</html>
<style>
    * {
    margin: 0;
    box-sizing: border-box;

}

a {
    text-decoration: none;
    color: white;
}

main {
    height: 800px;
    width: 450px;
    padding: 50px 0;
    border: #EFEFEF solid 2px;
    margin: 100px auto;
    text-align: center;
    display: flex;
    flex-direction: column;
}

.logo {
    margin-bottom: 50px;
    font-size: 50px;
    font-family: 'Lobster', cursive;
}

input {
    height: 45px;
    width: 300px;
    margin-bottom: 10px;
    background-color:#FAFAFA;
    border: #EFEFEF 1px solid;
    border-radius: 6px;
    padding-left: 10px;
}

input:focus {
    outline: none;
}

.login_btn {
    width: 300px;
    height: 35px;
    border-radius: 6px;
    border: white;
    margin-bottom: 100px;
    background-color: #C4E1FB;
    color: white;
    font-size: 17px;
}

.login_btn:hover {
    cursor: pointer;
}

footer {
    color: #345E87;
}
.noneunderline {
    text-decoration:none;
}
.haveAccount {
    background-color: #fcfcfc;
    margin-top: 10px;
    padding: 15px;
    border: 1px solid #dfdfdf;
    border-radius: 3px;
}

.haveAccount p {
    font-size: 14px;
    font-weight: 300;
    color: #333333;
}

.haveAccount p a{
    font-weight: 600;
    color: #248ae3;
}
.box {
  height: 50px;
}
    </style>

mysite/templates/search/stock_search.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Westagram</title>
    <link rel=stylesheet href="style/login.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
</head>
<body>
    <main>
        <div class="logo">주식 존망</div>
        <article>
        <form method="post" class="post-form" action="{% url 'search:data_search' %}" enctype="multipart/form-data">
        {% csrf_token %}
            {% for message in messages %}
          <p class="message">{{ message }}</p>
            {% endfor %}
            <label >시작일</label>
            <div class="date1">
                <input type="date" name="startdate" placeholder="시작일" class="datevalue">
            </div>
            <label >종료일</label>
            <div class="date2">
                <input type="date" name="finishdate" placeholder="종료일" class="dateValue">
            </div>
            <div class="search-box">

                <input type="text"  name="stock_name" class="search-txt" placeholder="검색">
                <a class="search-btn" href="#">
                  <i class="fas fa-search"></i>
                </a>
              </div>
              <button class="down_btn" type="submit">다운로드</button>
         </form>

            <form action="{% url 'search:stock_data_graph'  %}">
              <button class="graph_btn" type=submit>GRAPH</button>
            </form>
            <div class="box">
            <div class="horizonAndOrWrap">
                <hr class="leftHr">
                <div class="or">또는</div>
                <hr class="rightHr">
            </div>
            <div class="noneunderline"></div>
        </div></article>

        <div class="haveAccount">
            {% if user.is_authenticated %}
            <p>
                <a onclick="return confirm('정말 로그아웃하시겠습니까?');" class="noneunderline" href="{% url 'common:logout' %}">{{ user.first_name }}님 Logout</a>
            </p>
        </div>
        <div class="haveAccount">
             <p>
                <a href="{% url 'search:change_pw' %}" class="noneunderline">회원정보 변경</a>
            </p>
            {% endif %}
        </div>
    </main>
    <script src='./js/login.js'></script>
</body>
</html>
<style>
    * {
    margin: 0;
    box-sizing: border-box;
}
a {
    text-decoration: none;
    color: white;
}
main {
    height: 800px;
    width: 450px;
    padding: 50px 0;
    border: #EFEFEF solid 2px;
    margin: 100px auto;
    text-align: center;
    display: flex;
    flex-direction: column;
}
.logo {
    margin-bottom: 50px;
    font-size: 50px;
    font-family: 'Lobster', cursive;
}

input {
    height: 45px;
    width: 300px;
    margin-bottom: 10px;
    background-color:#FAFAFA;
    border: #EFEFEF 1px solid;
    border-radius: 6px;
    padding-left: 10px;
}
input:focus {
    outline: none;
}

.graph_btn {
    width: 300px;
    height: 35px;
    border-radius: 6px;
    border: white;
    margin-bottom: 100px;
    background-color: #ccaeb6;
    color: white;
    font-size: 17px;


}

.login_btn:hover {
    cursor: pointer;
}
.down_btn{
    width: 300px;
    height: 35px;
    border-radius: 6px;
    border: white;
    margin-top: 40px;
    margin-bottom: 10px;
    background-color: #b5cbd8;
    color: white;
    font-size: 17px;
}
footer {
    color: #345E87;
}
.noneunderline {
    text-decoration:none;
}
.haveAccount {
    background-color: #fcfcfc;
    margin-top: 10px;
    padding: 15px;
    border: 1px solid #dfdfdf;
    border-radius: 3px;
}

.haveAccount p {
    font-size: 14px;
    font-weight: 300;
    color: #333333;
}

.haveAccount p a{
    font-weight: 600;
    color: #248ae3;
}
.box {
  height: 50px;
}
.message{
 font-weight: bolder;
}
    </style>